# The URL the site will be built for
base_url = "https://www.mercurylayer.com"

compile_sass = true

build_search_index = false

theme = "juice"

[extra]
juice_logo_name = "Mercury Layer"
juice_logo_path = "mercurywallet-icon.png"
juice_extra_menu = [
    { title = "Telegram", link = "https://t.me/mercurywallet" },
    { title = "Twitter", link = "https://twitter.com/mercury_wallet" },
    { title = "Github", link = "https://github.com/commerceblock/mercurylayer"}
]

repository_url = "https://github.com/commerceblock/mercurylayer"
